blog/urls.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    # (?P<year>)表示 year 参数, \d{4}表示数字 有4位,4位数字赋给 year.
    # [-\w]表示从符号'-'和\w表示的(字母,数字,下划线)中选择一个.
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name="post_list_by_tag"),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share,
        name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),

]

myblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL,
#                      document_root=settings.MEDIA_ROOT)

blog/models.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    # 之前写错成(models.Model)后,view中的Post.published.all()会报错,没有 all 方法
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                                            .filter(status='published')
    # todo get_queryset 函数的原理.


class Post(models.Model):
    class Meta:
        ordering = ('-publish', )

        def __str__(self):
            return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])

    STATUS_CHOICE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    # slug
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    # related_name的作用,可以使用User的实例 user.blog_posts 获得该表
    # 默认为post_set ,小写的模型名后加上 _set
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    # todo 这个 publish  created 有什么区别?为什么 timezone.now()会报错
    # timezone.now()的话只会在 models.py 读取时执行一次,timezone.now 会在每次创建新实例时执行.
    publish = models.DateTimeField(default=timezone.now)
    # auto_now_add 创建时自动设置为当前时间
    created = models.DateTimeField(auto_now_add=True)
    # auto_now 每次 save()时设置为现在时间
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICE,
                              default='draft')
    objects = models.Manager()  # the default manager
    published = PublishedManager()  # Our custom manager

    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/views.py
#!/usr/bin/python
# -*- coding:utf-8 -*-

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .form import EmailPostForm, CommentForm


class PostListView(ListView):
    # default is Post.objects.all()
    queryset = Post.published.all()
    # default is 'object_list'
    context_object_name = 'posts'
    # ListView 把 paginate 对象放在page_obj
    paginate_by = 3
    # default is 'blog/post_list.html'
    template_name = 'blog/post/list.html'


# 使用了 class PostListView(ListView)来代替
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = ''

    if request.method == 'POST':
        # A comment was posted
        # 将字典赋给data会自动转换成表单数据
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to database yet
            #  创建 modle 实例,但不写入数据库
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            # todo new_comment无法传到 template 中,{% if new_comment %} 无法为 True
            # view 中添加了 new_comment=''并将其传入 template 中,这样就可以解决问题,但书上错了?还是有什么没注意到的地方
            new_comment.save()
    else:
        #  现在是非 POST 方法时会生成 CommentForm 的实例,那么当提交了 POST 后呢?
        #  生成了之后就会一直保存在页面内
        comment_form = CommentForm()

        # List of similar posts
        # 当前 post的所有 tag的 id
        # flat=True : [1, 2, 3] ; flat=False: [(1,), (2, ), (3, )]
    post_tags_ids = post.tags.values_list('id', flat=True)
    # print(post_tags_ids)
    # todo tags__in
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    # annotate 相对于 all,多给返回的 queryset 加了一个Count 方法,可以使用 post.same_tags
    # Count 计算 该post有多少 tags,赋值起别名same_tags = tags__count
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'new_comment': new_comment,
                   'similar_posts': similar_posts})


def post_share(request, post_id):

    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            # a dictionary of valid value
            cd = form.cleaned_data
            # send email
            # post.get_absolute_url()得到页面的地址/blog/2016/10/18/one-more-post/
            # request.build_absolute_uri 加上HTTP scheme 和 hostname
            # <http://>HTTP scheme   <myweb.site>hostname
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            # format中的每一个值会对应的替换一个{}
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'wo409697458@163.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <a href='/blog/'><h2>yakumo17s</h2></a>
            <p>yakumo17s的blog. 现共有 {% total_posts %} 篇. </p>
            <p><a href="{% url 'blog:post_feed' %}">分享</a></p>
        {% show_latest_posts 6 %}
        <h3>最多评论</h3>

        <!-- 引入变量需先赋值,不然会直接在 template显示出列表 -->
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">标签: {{ post.tags.all | join:", " }}</p>
    <p class="date">
        <!- 发布时间 {{ post.publish }} 作者 {{ post.author }} ->
    </p>
    {{ post.body | markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            分享该文章
        </a>
    </p>

    <h2>相关文章</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title}}</a>
        </p>
    {% empty %}
        没有相关文章.
    {% endfor %}

    <!-- the number of comments -->
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} 条评论 //{{total_comments|pluralize}}
        </h2>
    {% endwith %}


    <!-- display all comment -->
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>尚无评论.</p>
    {% endfor %}


    <!-- comment form -->
    {% if new_comment %}
        <h2>评论已添加.</h2>
    {% else %}
        <h2>添加新评论</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="提交"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}blog{% endblock %}

{% block content %}
    <h1>主页</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            标签:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloog.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            <!- Published {{ post.publish }} by {{ post.author }} ->
        </p>
        <!-- truncatewords 截取部分字符, linebreak会自动在有一空行段落前后加<p>,无空行段落加<br /> -->
        {{ post.body | markdown | truncatewords_html:30 }}
        <br /><br /><br />
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}分享文章{% endblock %}

{% block content %}
    {% if sent %}
        <h1>邮件发送成功</h1>
        <!-- todo注意下这里的cd.to的使用,cd -->
        <p>
            "{{ post.title }}" 已成功发送到 {{ cd.to }}.
        </p>
    {% else %}
        <h1>分享 "{{ post.title }}" </h1>
        <form action="." method="post">
            <!-- as.p 让每个输入框在一个<p>标签中 -->
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="发送邮件">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>